theme: jekyll-theme-cayman

<<<<<<< HEAD

=======
>>>>>>> 518745070f891f26830c2562225f50aec57a9114
     <head>
         <title>Home</title>
     </head>
  <style>
   <link rel="stylesheet" href="aquatiger.github.io/style.css" type="text/css">
  </style>
     <body>
         <header>
             A header that stays stuck to the top.
         </header>
         <nav>
             <ul>
             <li>About</li>
             <li>Papers</li>
             <li>Donate</li>
             </ul>
         </nav>
         <section>
             This would be a good place for a table of contents
         </section>
         <aside>
             This is the main content area
             <img src="http://interactivepython.org/runestone/static/webfundamentals/_images/img_sem_elements.gif" />
         </aside>
         <footer>
             Copyright Area, Contact Us.
         </footer>
     </body>
 </html>
